"""Add question_type and grading

Revision ID: 3be53a9ddc95
Revises: 6be8f84f6c40
Create Date: 2026-03-05 09:40:09.429609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3be53a9ddc95'
down_revision: Union[str, None] = '6be8f84f6c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.alter_column('chosen_answer',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('options',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teacher_grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_graded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_column('is_graded')
        batch_op.drop_column('teacher_grade')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('total_questions')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('options',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.drop_column('question_type')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.alter_column('chosen_answer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
